print ("aaaa" >=  "aaaa") 
print ("baaa" >=  "abaa")
print ("aaba" >=  "abaa")
print ("aaaa" == "aaaa")  
print ("aaaa" <= "zzzz")
print ("a" < "z") # orden alfabetico ("a" es la menor letra)("z" es la mayo letra)

print (len("a") < (len("aa")))# orden por cantidad de caracteres "a"(1) es menor que "aa"(2)

# operadores logicos (compuertas logicas)
print (2 < 4 and "a" > "b") 
print (len ("a") < len ("aa") or 8 > 15 )
print (len ("hola") == len("chau")) and (not(100<1))
print ("joaquin" > "zzzzzz")#cuento por VALOR de carateres (a menor que b)
print (len ("joaquin") > len ("zzzzzz"))#cuento por CANTIDAD de carateres (6 menor que 7)
